import = [
    "~/.config/alacritty/themes/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraCode"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape                 = "Beam"
blinking              = "Always"
