[general]
import = ["~/.config/alacritty/themes/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape                 = "Beam"
blinking              = "Always"
